#!/bin/bash
set -x

DISTRO=Armbian_21.02.1_Odroidxu4_buster_legacy_4.14.212.img.xz

[ -z "${1}" ] && { echo "Usage: $0 [DEVICE] # e.g. /dev/sdc"; exit; }
[ -f ${DISTRO} ] || {
	echo Distro not found.
	exit 1
}

set -x
xz -d - < ${DISTRO} | sudo dd of=${1} bs=4096
sync
